### ISSUE TITLE
Gizmo not respond to the rotation or translation

### ISSUE THREAD

**Issue by happydpc** [ForesightMiningSoftwareCorporation/bevy_transform_gizmo#16]
When manipulating the gizmo, the gizmo doesn't move with the drag.

**Comment by aevyrie** [comment]
Can you provide any more details? Does this happen with the provided minimal example?

**Comment by happydpc** [comment]
Here you can see the gizmo didn't rotate with the drag.

https://user-images.githubusercontent.com/771776/150466907-499f7985-8968-4957-8b6e-384d0cbfd370.mp4
