### ISSUE TITLE
Add a gizmo to whole scene

### ISSUE THREAD

**Issue by aevyrie** [ForesightMiningSoftwareCorporation/bevy_transform_gizmo#20]
@elpiel: creating this issue to discuss your question from your PR
https://github.com/ForesightMiningSoftwareCorporation/bevy_transform_gizmo/pull/18#issuecomment-1025533979

> Btw is there a way to add the gizmo to a whole scene?

Could you provide a bit more detail? Do you want to:
1. Select everything in the scene and transform it
2. Make everything in the scene possible to transform individually
3. Something else?

**Comment by elpiel** [comment]
Iirc it was the 1.
We had a drone 3D model loaded as a whole scene, but I was unable to add the gizmo to the whole scene.

**Comment by aevyrie** [comment]
In that case, you probably want to add the `GizmoTransformable` to the parent object. You can also use ctrl+a to select everything.

**Comment by sajattack** [comment]
> In that case, you probably want to add the `GizmoTransformable` to the parent object. You can also use ctrl+a to select everything.

This definitely doesn't work :(
