### ISSUE TITLE
Update to Bevy 0.9

### ISSUE THREAD

**Issue by olegomon** [ForesightMiningSoftwareCorporation/bevy_transform_gizmo#41]
As of today Bevy is 2 open issues behind the 0.9 milestone. See: https://github.com/bevyengine/bevy/milestone/7 and this crate should support it asap ;)

Bevy Migration

remove deprecated API usage of `spawn_bundle()` and use `spawn()` instead

**Comment by hate** [comment]
Requesting to close this issue, crate has since been updated to version 0.10 :).
